// import "@/app/globals.css";
export const metadata = {
  title: "Clothing Store",
  description: "Generated by create next app",
};
import Header from "@/Component/AdminHeader/Header";
import MobileHeader from "@/Component/AdminHeader/MobileHeader";
import Footer from "@/Component/Footer";
// import ProtectAdminRoute from "@/app/AdminDashboard/ProtectAdminRoute";
export default function RootLayout({ children }) {
  return (
    <>
      {/* <ProtectAdminRoute /> */}
      <MobileHeader />
      <Header />
      {children}
      <Footer />
    </>
  );
}
