import "./globals.css";
import StoreProvider from "./StoreProvider";
import CheckLogin from "./CheckLogin";
export const metadata = {
  title: "Clothing Store",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <CheckLogin />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
