import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "AI Career Assistant",
  description: "Generated by create next app",
};
import Header from "@/Component/Header";
import MobileHeader from "@/Component/MobileHeader";
import Footer from "@/Component/Footer";
export default function RootLayout({ children }) {
  return (
    <>
      <MobileHeader />
      <Header />
      {children}
      <Toaster position="top-center" reverseOrder={false} />
      <Footer />
    </>
  );
}
