"use client";
import DisplayResume from "@/Component/DisplayResume";
import ResumeForm from "@/Component/Form/ResumeForm";
import ResumePreview from "@/Component/ResumePreview";

import { ResetResume } from "@/Libraries/Slices/Resume/ResumeSlice";
import { useState, useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
const page = () => {
  let dispatch = useDispatch();
  let { loading, success } = useSelector((state) => state.ResumeSlice);

  //to preview the data in resume preview section
  const [previewData, setPreviewData] = useState({});

  // Reset resume when user leaves this page
  useEffect(() => {
    return () => {
      dispatch(ResetResume());
    };
  }, [dispatch]);

  return (
    <div className="min-h-screen bg-gray-100 p-5 sm:p-10 2xl:p-20">
      <h1 className="text-xl sm:text-3xl 2xl:text-4xl font-bold mb-6">
        Resume Details
      </h1>
      <div className="grid grid-cols-1 sm:grid-cols-2 sm:justify-between">
        <ResumeForm onDataChange={setPreviewData} />
        <div className="lg:block my-5 ">
          {success === false ? (
            //it will show preview
            <ResumePreview data={previewData} />
          ) : (
            //it will shwo the full resume which si generated by a ai
            <DisplayResume />
          )}
        </div>
      </div>
    </div>
  );
};

export default page;
