"use client";
import DownloadPDF from "@/Component/Buttons/DownloadPDF";
import DisplayResume from "@/Component/DisplayResume";
import ResumeForm from "@/Component/Form/ResumeForm";
import ResumePreview from "@/Component/ResumePreview";
import ResumeSkeleton from "@/Component/ResumeSkeleton";

import { ResetResume } from "@/Libraries/Slices/Resume/ResumeSlice";
import { useState, useEffect, useRef } from "react";
import { useSelector, useDispatch } from "react-redux";

//remaining api calls per day
import RemainingAPICalls from "@/Component/RemainingAPICalls";

const page = () => {
  const previewRef = useRef(null); // Create the reference
  let dispatch = useDispatch();
  let { success, loading, errorMessage } = useSelector(
    (state) => state.ResumeSlice,
  );

  // get remainingCalls from a interivew slice and also here it is used to show the remining number of a calls
  let { remainingCalls, ShowPopUp } = useSelector(
    (state) => state.InterviewSlice,
  );

  //to preview the data in resume preview section
  const [previewData, setPreviewData] = useState({});

  // Reset resume when user leaves this page
  useEffect(() => {
    return () => {
      dispatch(ResetResume());
    };
  }, [dispatch]);

  // Automatically scroll when success becomes true
  useEffect(() => {
    if ((success || loading) && previewRef.current) {
      previewRef.current.scrollIntoView({
        behavior: "smooth",
        block: "start",
      });
    }
  }, [success, loading]);

  //these are used to ceck that if a user is login or signup  if user is login than it will show ther remaining number of a api calls
  let { Role } = useSelector((state) => state.SignUpSlice);

  //login role
  let { UserRole } = useSelector((state) => state.LogInSlice);

  useEffect(() => {
    if (errorMessage) {
      alert(errorMessage);
    }
  }, [errorMessage]);

  //show the resume sekeleton when move to a remuse section
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return <ResumeSkeleton />;
  }

  return (
    <div className="min-h-screen overflow-x-hidden bg-gray-100 p-5 sm:p-10 2xl:p-20">
      {(Role === "User" || UserRole === "User") &&
        (success ||
          errorMessage ||
          remainingCalls === 0 ||
          //show popups is also use to show the popup when thre remaining calls is greater than a 0 brother 
          ShowPopUp === true) && (
          <RemainingAPICalls remaining={remainingCalls} />
        )}

      <div className=" flex justify-between">
        <h1 className="text-xl sm:text-3xl  xl:text-4xl font-bold my-6 lg:my-10 text-slate-800">
          AI Resume Builder
        </h1>
        <h2 className="hidden lg:block lg:my-10">
          <DownloadPDF />
        </h2>
      </div>

      <div className="grid grid-cols-1  md:grid-cols-2">
        <ResumeForm onDataChange={setPreviewData} />
        <div ref={previewRef} className="lg:block my-5 ">
          {/* when loading is true than show the resume skeleton  */}
          {loading ? (
            <ResumeSkeleton />
          ) : success === false ? (
            //it will show preview and it is show during when we fill the form
            <ResumePreview data={previewData} />
          ) : (
            //it will shwo the full resume which si generated by a ai
            <DisplayResume />
          )}
        </div>
      </div>
    </div>
  );
};

export default page;
