import "./globals.css";
import StoreProvider from "./StoreProvider";
import CheckLogin from "./CheckLogin";
export const metadata = {
  title: "AI Career Assistant",
  description: "Generated by create next app",
  icons: { icon: "/logo.png" },
};

// /for toast
import { Toaster } from "react-hot-toast";

import Header from "@/Component/Header";
import MobileHeader from "@/Component/MobileHeader";
import Footer from "@/Component/Footer";

import { GoogleOAuthProvider } from "@react-oauth/google";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        >
          <StoreProvider>
            <CheckLogin />

            {/* header and also mobile heaer */}
            <MobileHeader />
            <Header />

            {children}
            {/* toast an also foother */}
            <Toaster position="top-center" reverseOrder={false} />
            <Footer />
          </StoreProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
