// import "@/app/globals.css";

export const metadata = {
  title: "Clothing Store",
  description: "Generated by create next app",
};
import Header from "@/Component/Header";
import MobileHeader from "@/Component/MobileHeader";
import Footer from "@/Component/Footer";
export default function RootLayout({ children }) {
  return (
    <>
      <MobileHeader />
      <Header />
      {children}
      <Footer />
    </>
  );
}
